
USE ATLAS_MODULE, ONLY : ATLAS_LIBRARY, ATLAS_LOG, ATLAS_REDUCEDGAUSSIANGRID, &
                       & ATLAS_GRID

USE FA_MOD, ONLY : FA_COM_DEFAULT, NEW_FA_DEFAULT, FACADR

USE PARKIND1, ONLY : JPRB, JPIM

IMPLICIT NONE


CHARACTER (LEN=*), PARAMETER :: CLNOMC = 'c'
INTEGER (KIND=JPIM)   :: ILUN, IREP, INBARP, INBARI


INTEGER, PARAMETER :: NDGLG = 32
INTEGER :: NLOENG (NDGLG) = &
[ 20, 30, 40, 48, 54, 60, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, &
& 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 60, 54, 48, 40, 30, 20 ]

TYPE (ATLAS_REDUCEDGAUSSIANGRID) :: GRID

REAL (8), PARAMETER :: LATITUDEoFsTRETCHINGpOLEiNdEGREES = 46.4688;
REAL (8), PARAMETER :: LONGITUDEoFsTRETCHINGpOLEiNdEGREES = 2.57831;
REAL (8), PARAMETER :: STRETCHINGFACTOR = 2.4;

INTEGER :: IX, IY

CALL ATLAS_LIBRARY%INITIALISE()


GRID = ATLAS_REDUCEDGAUSSIANGRID (NLOENG, [LONGITUDEOFSTRETCHINGPOLEINDEGREES, &
                                & LATITUDEOFSTRETCHINGPOLEINDEGREES], STRETCHINGFACTOR)

PRINT *, " SIZE = ", GRID%SIZE ()

DO IY = 1, GRID%NY ()
  DO IX = 1, GRID%NX (IY)
    WRITE (*, '(2F20.10)') GRID%LONLAT (IX, IY)
  ENDDO
ENDDO

CALL GRID%FINAL ()

CALL ATLAS_LIBRARY%FINALISE()

END 

