PROGRAM ATLAS_ARPEGE_F

USE ATLAS_ARPEGE_MODULE

USE MODD_IO_SURF_ARO,  ONLY : SURFEX_FIELD_BUF_CACHE,      &    
                            & SURFEX_FIELD_BUF_ADD,        &
                            & SURFEX_FIELD_BUF_WRITE_MISC, &
                            & SURFEX_FIELD_BUF_DEALLOC


USE PARKIND1, ONLY : JPRB, JPIM

IMPLICIT NONE

#include "abor1.intfb.h"

CHARACTER (LEN=16), PARAMETER :: CLPREF (*) = &
[ 'SURF            ', 'PROF            ', 'PROF            ', &
  'SURF            ', 'SURF            ', 'SURF            ', &
  'SURF            ', 'SURF            ', 'SURF            ', &
  'SURF            ', 'SURF            ', 'SURF            ', &
  'SURF            ', 'SURF            ', 'SURF            ']

INTEGER (KIND=JPIM), PARAMETER :: INIVAU (*) = &
[ 0_JPIM            , 0_JPIM            , 0_JPIM            , &
  0_JPIM            , 0_JPIM            , 0_JPIM            , &
  0_JPIM            , 0_JPIM            , 0_JPIM            , &
  0_JPIM            , 0_JPIM            , 0_JPIM            , &
  0_JPIM            , 0_JPIM            , 0_JPIM            ]

CHARACTER (LEN=16), PARAMETER :: CLSUFF (*) = &
[ 'TEMPERATURE     ', 'TEMPERATURE     ', 'RESERV.EAU      ', &
  'RESERV.NEIGE    ', 'RESERV.EAU      ', 'Z0.FOIS.G       ', &
  'ALBEDO          ', 'EMISSIVITE      ', 'ET.GEOPOTENT    ', &
  'IND.TERREMER    ', 'PROP.VEGETAT    ', 'VAR.GEOP.ANI    ', &
  'VAR.GEOP.DIR    ', 'IND.VEG.DOMI    ', 'RESI.STO.MIN    ']

INTEGER (KIND=JPIM), PARAMETER :: INFLD = 10


TYPE (ATLAS_STRUCTUREDGRID)            :: YLGRID
TYPE (ATLAS_MESH)                      :: YLMESH
TYPE (ATLAS_CONFIG)                    :: YLCONF
TYPE (ATLAS_MESHGENERATOR)             :: YLMESHGEN
TYPE (ATLAS_GRIDDISTRIBUTION)          :: YLDIST
TYPE (ATLAS_FUNCTIONSPACE_NODECOLUMNS) :: YLNDCO
TYPE (ATLAS_FIELDSET)                  :: YLFLSL
TYPE (FCKIT_MPI_COMM)                  :: YLCOMM



INTEGER :: IX, IY, I, J

INTEGER :: IRANK

CHARACTER (LEN=64) :: CLFILENAME

CALL GETARG (1, CLFILENAME)

CALL ATLAS_LIBRARY%INITIALISE()

YLCOMM = FCKIT_MPI_COMM ()
IRANK = YLCOMM%RANK ()

WRITE (*, *) __FILE__, ':', __LINE__, " IRANK = ", IRANK

CALL GFA (CLFILENAME, YLGRID)

PRINT *, " SIZE = ", YLGRID%SIZE ()

DO IY = 1, INT (YLGRID%NY (), JPIM)
  DO IX = 1, INT (YLGRID%NX (IY), JPIM)
    WRITE (*, '(2F20.10)') YLGRID%LONLAT (IX, IY)
  ENDDO
ENDDO

YLMESHGEN = ATLAS_MESHGENERATOR ()

YLCONF    = ATLAS_CONFIG()
CALL YLCONF%SET ('type', 'equal_regions')
!CALL YLCONF%SET ('type', 'checkerboard')
YLDIST    = ATLAS_GRIDDISTRIBUTION (YLGRID, YLCONF)
CALL YLCONF%FINAL ()

PRINT *, " YLDIST%NB_PARTITIONS () = ", YLDIST%NB_PARTITIONS ()

DO I = 1, INT (YLGRID%SIZE (), JPIM)
  WRITE (*, '(I6,I6)') I, YLDIST%PARTITION (I)
ENDDO

YLMESH    = YLMESHGEN%GENERATE (YLGRID, YLDIST)
YLNDCO    = ATLAS_FUNCTIONSPACE_NODECOLUMNS (YLMESH)
YLFLSL    = ATLAS_FIELDSET ()

CALL RFA (CLFILENAME, YLGRID, YLNDCO, CLPREF (1:INFLD), &
        & INIVAU (1:INFLD), CLSUFF (1:INFLD), YLFLSL)


PRINT *, " YLFLSL%SIZE = ", YLFLSL%SIZE ()

CALL WFA (TRIM (CLFILENAME)//'.out', YLGRID, YLNDCO, CLPREF (1:INFLD), &
        & INIVAU (1:INFLD), CLSUFF (1:INFLD), YLFLSL)

BLOCK
  REAL (KIND=JPRB), POINTER :: ZFLDL (:)
  TYPE (ATLAS_FIELD) :: YLFLD

  DO J = 1, YLFLSL%SIZE ()
    YLFLD = YLFLSL%FIELD (J)

    ZFLDL => NULL ()
    CALL YLFLD%DATA (ZFLDL)

    WRITE (*, '("LOCAL ",A16,I16,E12.4)') YLFLD%NAME (), SIZE (ZFLDL), SUM (ZFLDL) / SIZE (ZFLDL)

    CALL YLFLD%FINAL ()
  ENDDO
ENDBLOCK


CALL YLFLSL%FINAL ()

CALL YLDIST%FINAL ()
CALL YLMESH%FINAL ()

CALL YLMESHGEN%FINAL ()
CALL YLGRID%FINAL ()


CALL ATLAS_LIBRARY%FINALISE()

END PROGRAM

